apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hellotest
  name: hellotest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellotest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hellotest
    spec:
      containers:
      - image: replaceme
        name: replaceme
        resources: {}
status: {}
