apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hellotest
  name: hellotest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellotest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hellotest
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: omargo:0.1
        imagePullPolicy: Never
        name: replaceme
        resources: {}
status: {}
